### ISSUE TITLE
Question about tree-shaking

### ISSUE THREAD

**Issue by testacode** [gVguy/rollup-ts-boilerplate#1]
If I lay my components library here, will it be tree shakable compatible?

**Comment by gVguy** [comment]
By default `npm run build` will bundle your code to 3 formats: iife, cjs and esm (which is tree-shakeable yes)

Of course, this is just a starting point. You can always modify rollup.config.js to suit your needs :)

Here's what rollup docs [has to say](https://rollupjs.org/guide/en/#tree-shaking) about tree-shaking.
